//! Generated by cot CLI 0.2.2 on 2025-05-01 08:14:44+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "m4txblog";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] = &[
        ::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("comment"))
            .fields(
                &[
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("id"),
                            <cot::db::Auto<i32> as ::cot::db::DatabaseField>::TYPE,
                        )
                        .auto()
                        .primary_key()
                        .set_null(
                            <cot::db::Auto<i32> as ::cot::db::DatabaseField>::NULLABLE,
                        ),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("post_id"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("username"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                    ::cot::db::migrations::Field::new(
                            ::cot::db::Identifier::new("text"),
                            <String as ::cot::db::DatabaseField>::TYPE,
                        )
                        .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ],
            )
            .build(),
        ::cot::db::migrations::Operation::add_field()
            .table_name(::cot::db::Identifier::new("comment"))
            .field(
                ::cot::db::migrations::Field::new(
                        ::cot::db::Identifier::new("parent"),
                        <cot::db::ForeignKey<
                            crate::comments::Comment,
                        > as ::cot::db::DatabaseField>::TYPE,
                    )
                    .foreign_key(
                        <crate::comments::Comment as ::cot::db::Model>::TABLE_NAME,
                        <crate::comments::Comment as ::cot::db::Model>::PRIMARY_KEY_NAME,
                        ::cot::db::ForeignKeyOnDeletePolicy::Restrict,
                        ::cot::db::ForeignKeyOnUpdatePolicy::Restrict,
                    )
                    .set_null(
                        <cot::db::ForeignKey<
                            crate::comments::Comment,
                        > as ::cot::db::DatabaseField>::NULLABLE,
                    ),
            )
            .build(),
    ];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Comment {
    #[model(primary_key)]
    id: cot::db::Auto<i32>,
    parent: cot::db::ForeignKey<crate::comments::Comment>,
    post_id: String,
    username: String,
    text: String,
}
